INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('If you rearrange the letters “LNGEDNA”, you have the name of a:', 'Country', 'Animal', 'Ocean', 'River', 'A'),
('Which of these is an odd number?', '4', '10', '17', '20', 'C'),
('What is 14 × 3?', '42', '36', '48', '40', 'A'),
('Which planet is known for its rings?', 'Mars', 'Jupiter', 'Saturn', 'Venus', 'C'),
('What is 20% of 250?', '40', '45', '50', '55', 'C'),
('Which number completes the sequence: 5, 10, 20, 40, ?', '60', '70', '80', '100', 'C'),
('If 4 pencils cost 40 shillings, what is the cost of 10 pencils?', '80', '90', '100', '120', 'C'),
('Which word is the odd one: Dog, Cat, Tiger, Rose?', 'Tiger', 'Rose', 'Dog', 'Cat', 'B'),
('What is the capital of Canada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 'B'),
('Which planet is farthest from the Sun?', 'Earth', 'Saturn', 'Neptune', 'Jupiter', 'C'),
('Which shape has 8 sides?', 'Pentagon', 'Hexagon', 'Octagon', 'Nonagon', 'C'),
('What is 7 cubed?', '343', '56', '77', '144', 'A'),
('Which one is a mammal?', 'Shark', 'Whale', 'Octopus', 'Frog', 'B'),
('Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen', 'B'),
('Which is the square root of 144?', '12', '14', '10', '16', 'A'),
('If 60 ÷ 3 = 20, what is 60 ÷ 5?', '15', '12', '18', '10', 'A'),
('Which is the largest desert in the world?', 'Sahara', 'Gobi', 'Kalahari', 'Antarctica', 'D'),
('Which gas do plants produce during photosynthesis?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen', 'B'),
('How many continents are there?', '5', '6', '7', '8', 'C'),
('Which day comes after Friday?', 'Thursday', 'Saturday', 'Sunday', 'Monday', 'B'),
('What is the boiling point of water at sea level?', '90°C', '100°C', '110°C', '120°C', 'B'),
('Who discovered gravity?', 'Newton', 'Einstein', 'Galileo', 'Archimedes', 'A'),
('What is the currency of Japan?', 'Dollar', 'Yen', 'Peso', 'Won', 'B'),
('Which blood group is a universal donor?', 'O-', 'AB', 'A+', 'B-', 'A'),
('What is 3/4 of 200?', '100', '120', '150', '160', 'C'),
('Which country has the Eiffel Tower?', 'Italy', 'France', 'Spain', 'Germany', 'B'),
('How many degrees in a right angle?', '45', '60', '90', '180', 'C'),
('Which instrument measures temperature?', 'Barometer', 'Thermometer', 'Hygrometer', 'Altimeter', 'B'),
('What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kisumu', 'Dodoma', 'A'),
('What is 100 ÷ 25?', '2', '3', '4', '5', 'C'),
('Which planet is called the Morning Star?', 'Mercury', 'Venus', 'Mars', 'Saturn', 'B'),
('How many letters are there in the English alphabet?', '24', '25', '26', '27', 'C'),
('Which is not a primary color?', 'Red', 'Blue', 'Green', 'Yellow', 'C'),
('What is the fastest land animal?', 'Cheetah', 'Leopard', 'Lion', 'Horse', 'A'),
('Which is the largest mammal?', 'Elephant', 'Blue Whale', 'Shark', 'Giraffe', 'B'),
('What is the chemical symbol for Gold?', 'Ag', 'Au', 'Gd', 'Go', 'B'),
('Which gas do we exhale?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Helium', 'B'),
('Which fruit has seeds on its outside?', 'Apple', 'Strawberry', 'Banana', 'Mango', 'B'),
('How many planets are in our solar system?', '7', '8', '9', '10', 'B'),
('Which planet is known as the “Blue Planet”?', 'Earth', 'Neptune', 'Uranus', 'Saturn', 'A'),
('Which is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B'),
('What is 2 to the power of 5?', '10', '32', '16', '25', 'B'),
('Which is the coldest planet?', 'Neptune', 'Uranus', 'Pluto', 'Saturn', 'A'),
('What is the smallest ocean in the world?', 'Atlantic', 'Indian', 'Arctic', 'Southern', 'C'),
('Which is the capital of Tanzania?', 'Arusha', 'Dodoma', 'Dar es Salaam', 'Zanzibar', 'B'),
('Which animal has a long trunk?', 'Lion', 'Elephant', 'Giraffe', 'Hippo', 'B'),
('What is 5 factorial (5!)?', '20', '60', '120', '100', 'C'),
('Which is the hardest natural substance?', 'Diamond', 'Iron', 'Steel', 'Gold', 'A'),
('Which month of the year has the fewest days?', 'February', 'April', 'June', 'November', 'A'),
('What is the capital of China?', 'Beijing', 'Shanghai', 'Hong Kong', 'Shenzhen', 'A'),
('Which part of the plant conducts photosynthesis?', 'Root', 'Stem', 'Leaf', 'Flower', 'C'),
('Which planet is known as Earth’s twin?', 'Mars', 'Venus', 'Mercury', 'Saturn', 'B'),
('What is the speed of light?', '300,000 km/s', '150,000 km/s', '100,000 km/s', '500,000 km/s', 'A'),
('What is the opposite of “Cold”?', 'Hot', 'Cool', 'Warm', 'Heat', 'A'),
('Which shape has four equal sides?', 'Triangle', 'Square', 'Rectangle', 'Pentagon', 'B'),
('Which bird cannot fly?', 'Eagle', 'Ostrich', 'Sparrow', 'Crow', 'B'),
('Which is the tallest building in the world (as of 2025)?', 'Shanghai Tower', 'Burj Khalifa', 'One World Trade Center', 'Taipei 101', 'B'),
('Which planet has the most moons?', 'Mars', 'Saturn', 'Jupiter', 'Neptune', 'C'),
('Which country is the largest by land area?', 'Canada', 'China', 'Russia', 'USA', 'C'),
('Which part of the body pumps blood?', 'Brain', 'Heart', 'Lungs', 'Liver', 'B'),
('How many minutes are in 2 hours?', '100', '120', '140', '160', 'B'),
('Which is the lightest metal?', 'Gold', 'Lithium', 'Aluminium', 'Iron', 'B'),
('Which planet has a giant storm called the Great Red Spot?', 'Saturn', 'Jupiter', 'Mars', 'Venus', 'B'),
('Which color do you get when you mix yellow and blue?', 'Green', 'Orange', 'Purple', 'Pink', 'A'),
('Which planet has the shortest day?', 'Mercury', 'Saturn', 'Jupiter', 'Mars', 'C'),
('Which is the largest island in the world?', 'Greenland', 'Australia', 'Madagascar', 'New Guinea', 'A'),
('How many strings does a standard guitar have?', '4', '5', '6', '7', 'C'),
('What is 90 ÷ 9?', '10', '9', '8', '7', 'A');
